### ISSUE TITLE
Any other similar project?

### ISSUE THREAD

**Issue by piotr-yuxuan** [quoll/kanonas#9]
Hello here,

That draft which sounds promising but the readme itself states that 'it doesn't work'. Have you heard about any similar project which actually plans to work?

**Comment by quoll** [comment]
Ah, I should update this project!

This was originally a personal project. But then my employer took it on, so we moved it, and renamed it. It does much more now.

https://github.com/threatgrid/naga

I also presented it at Clojure/conj 2016
https://youtu.be/8rRzESy0X2k
